core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('posts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path, include

from rest_framework.routers import DefaultRouter

from .views import (
    PostsListView, 
    PostCreateView,
    PostDetailView,
    PostsAPIView, 
)

router = DefaultRouter()
router.register(r"posts", PostsAPIView, "posts")

app_name = "posts"
urlpatterns = [
    path('', PostsListView.as_view(), name="home"),
    path('posts/create/', PostCreateView.as_view(), name="create"),
    path('posts/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    # API Urls
    path('api/', include(router.urls))
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=255, null=False)
    body = models.TextField(null=False)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

posts/forms.py
from django import forms

from .models import Post


class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'body']

posts/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import View, DetailView, FormView

from rest_framework.exceptions import PermissionDenied
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.viewsets import ModelViewSet

from .models import Post
from .forms import CreatePostForm
from .serializers import PostSerializer


TEMPLATE_FOLDER_NAME = 'posts'

class PostsListView(View):
    template_name = f"{TEMPLATE_FOLDER_NAME}/post_list.html"
    def get(self, request):
        return render(request, self.template_name, {})

class PostDetailView(DetailView):
    model = Post
    template_name = f'{TEMPLATE_FOLDER_NAME}/post_detail.html'
    context_object_name = 'post'

# class PostAddView():

class PostCreateView(LoginRequiredMixin, FormView):
    model = Post
    template_name = f"{TEMPLATE_FOLDER_NAME}/post_form.html"
    success_url = reverse_lazy('posts:home')

    def get(self, request, pk=None):
        form = CreatePostForm()
        context = {
            'form': form
        }
        return render(request, self.template_name, context)
    
    def post(self, request, *args, **kwargs):
        form = CreatePostForm(request.POST)
        if not form.is_valid():
            context = {
                "form": form
            }
            return render(request, self.template_name, context)
        post = form.save(commit=False)
        post.owner = request.user
        post.save()
        return redirect(self.success_url)


# API VIEWS

class PostsAPIView(ModelViewSet):
    serializer_class = PostSerializer
    queryset = Post.objects.all()

    def get_permissions(self):
        if self.action in ['list', 'retrieve']:
            return [AllowAny()]
        return [IsAuthenticated()]

    def update(self, request, *args, **kwargs):
        post = self.get_object()

        if post.owner != request.user:
            raise PermissionDenied("This isn't your POST, machine")
        
        return super().update(request, *args, **kwargs)
    
    def destroy(self, request, *args, **kwargs):
        post = self.get_object()

        if post.owner != request.user:
            raise PermissionDenied("This isn't your POST, machine")
        
        return super().destroy(request, *args, **kwargs)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" style="background-color: #a4cea4;">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django + Vue</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    {% block navbar %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block script %}
    {% endblock %}
</body>
</html>

templates/navbar.html
{% extends 'base.html' %}
{% load posts_tags %}

{% block navbar %}
<header class="line-bottom">
    <nav class="container flex-row justify-space-between alig-center pad-y-100">
        <div>
            <a href="{% url 'posts:home' %}" class="fw-800 fs-200">BlogPost</a>
        </div>
        <div>
            {% if request.user.is_authenticated %}
            <div class="flex-row gap-100 alig-center">
                <div>
                    <span>
                        {{ request.user.username }}
                        <a href="{% url 'posts:create' %}" class="button-small fs-090">New Post</a>
                    </span>
                </div>
                <div id="logout"></div>
            </div>
            {% else %}
            <a href="{% url 'login' %}?next={{ request.path }}" class="button-normal fs-090">Login</a>
            {% endif %}
        </div>
    </nav>
</header>
{% endblock %}

{% block script %}
    {% vue_tag 'auth' %}
{% endblock %}

templates/posts/post_detail.html
{% extends 'navbar.html' %}
{% load posts_tags %}

{% block content %}
<div class="pad-t-300">
    <div
        id="post-item" 
        data-user-id="{{ request.user.id }}" 
        data-post-id="{{ post.id }}"
        class="container flex-column gap-100"
    ></div>
</div>
{% endblock %}

{% block script %}
    {{ block.super }}
    {% vue_tag 'postDetail' %}
{% endblock %}

templates/posts/post_form.html
{% extends 'navbar.html' %}
{% block content %}
<div class="pad-t-300">
    <div class="container">
        <form action="{% url 'posts:create' %}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Create</button>
        </form>
    </div>
</div>
{% endblock %}

templates/posts/post_list.html
{% extends 'navbar.html' %}
{% load posts_tags %}


{% block content %}
<div class="pad-t-300">
    <div 
        id="posts-list" 
        data-user-id="{{ request.user.id }}"
        class="container"
    ></div>
</div>

{% endblock %}

{% block script %}
    {{ block.super }}
    {% vue_tag 'postsList' %}
{% endblock %}